name: CI/CD Pipeline for C# App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    # Paso 3: Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore

    # Paso 4: Construir el proyecto
    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest

    steps:
    # Repetir los pasos previos hasta la construcción
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-restore

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy (Simulated)
      run: |
        echo "Packaging the app for deployment"
        mkdir output
        cp -r ./bin/Debug/net7.0/* output/
        zip -r app.zip output/
